source 'https://rubygems.org'

# Specify your gem's dependencies in fastresize.gemspec
gemspec path: '../..'

group :development, :test do
  gem 'rake', '~> 13.0'
  gem 'rake-compiler', '~> 1.2'
  gem 'rspec', '~> 3.0'
  gem 'benchmark-ips', '~> 2.0'
end
